### ISSUE TITLE
Prüfen button and score calculation/rescoring

### ISSUE THREAD

**Issue by daalft** [Rostu/elearning#26]
Not all tasks check the answers immediately (e.g. generationen_task3). They require the user to click on a 'check' button. The score calculation and display is done only when clicked on that button. If the user made one or more mistakes and corrects these mistakes, clicking 'check' will add to the existing score. These tasks should either reset the score or score immediately (e.g. upon selecting a radio button). These tasks could also just be left the way they are. Any comments?

**Comment by Rostu** [comment]
I think that is a point we can discuss next week, since not everybody can see the issues.

**Comment by Rostu** [comment]
check buttons will be removed, and answers will be checked immediately.
